# Generated by Django 6.1.1 on 2026-09-28 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('fit_rationale', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('linkedin', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('not_contacted', 'Not Contacted'), ('sent', 'Sent'), ('replied', 'Opened/Replied'), ('in_conversation', 'In Conversation'), ('interview', 'Interview'), ('closed_won', 'Closed-Won'), ('closed_lost', 'Closed-Lost')], default='not_contacted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1000, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('drafted_message', models.TextField(blank=True)),
                ('sent', models.BooleanField(default=False)),
                ('auto_created', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='tracker.company')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('email', 'Email')], max_length=20)),
                ('direction', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='tracker.company')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
